# Numpy Basic

## 26feb 2023

In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


In [ ]:
Answer.
Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, which can hold elements of different data types. In this case, it contains strings.

The variable array_list is a NumPy array, which is a homogeneous data structure that can hold elements of a single data type.
In this case, it contains strings as well.

In [2]:
#To print the data types of both variables, you can use the type() function as follows
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
#Answer.
#Here's an example code that accomplishes this:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
* array_list = np.array(object = list_, dtype = int)
##### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
##### Consider the below code to answer further questions:
* import numpy as np
* num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
* num_array = np.array(object = num_list)

In [4]:
#Answer.
# Here's the code:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

print("\n---\n")

# Print data types of elements in array_list
print("Data types of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

---

Data types of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [5]:
#Answer.
# Here's the code:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
* [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
#Answer.
# Here's the code:
import numpy as np

zero_array = np.zeros((3, 3))

print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
* [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
#Answer.
# Here's the code:
import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
